Spring:
  application:
    name: CONFIG-PROD
eureka:
  instance:
    prefer-ip-address: true
    client-fetch-registry: true
    client:
      register-with-eureka: true
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
